### ISSUE TITLE
Can't use secrets to hide the passwords

### ISSUE THREAD

**Issue by UbioZur** [jasonmunro/cypht-docker#13]
Hi,
Trying out Cypht to find a good webmail.
I can't seem to be able to setup the secrets on the docker-compose to hide the passwords.

```
version: "3.5"
services:
  cypht:
    image: sailfrog/cypht-docker:latest
    container_name: cypht
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${HOME}/cypht/users:/var/lib/hm3/users
      - ${HOME}/cypht/app_data:/var/lib/hm3/app_data
    secrets:
      - cyphtpass
      - cyphtdbpass
    environment:
      - CYPHT_SESSION_TYPE=DB
      - CYPHT_AUTH_USERNAME=myuser
      - CYPHT_AUTH_PASSWORD_FILE=/run/secrets/cyphtpass
      - CYPHT_DB_CONNECTION_TYPE=host
      - CYPHT_DB_HOST=mariadb
      - CYPHT_DB_NAME=cypht
      - CYPHT_DB_USER=cypht
      - CYPHT_DB_PASS_FILE=/run/secrets/cyphtdbpass
      - CYPHT_DB_DRIVER=mysql
      - PUID=1000
      - PGID=1000
networks:
  # proxy network to enable container access to internet
  proxy:
    external: true
secrets:
  cyphtpass:
    file: ${HOME}/.secrets/cyphtpass
  cyphtdbpass:
    file: ${HOME}/.secrets/cyphtdbpass
```

It works fine without the secrets by putting the passwords (user and database) in clear in the file!

Any options to be able to hide those passwords would be welcome.
